### ISSUE TITLE
[Tema]: Como é trabalhar na Amazon

### ISSUE THREAD

**Issue by peixotoleonardo** [cassiobotaro/botaro-cassio-no-youtube#5]
### Mais detalhes

Falar sobre como está sendo sua experiencia em trabalhar na Amazon, como foi o processo e como você se preparou para passar na entrevista.

### Quadro

Botaro o Cássio no Youtube

**Comment by cassiobotaro** [comment]
@peixotoleonardo Obrigado por enviar o tema, já marquei para dezembro. https://www.youtube.com/watch?v=C0nxqhU3h80

cc @vitorStein
